import "./globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";

import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import MyToast from "@/components/child/toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Akshay: Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={inter.className}>
        <Navbar />
        {children}
        <MyToast />
        <Footer />
      </body>
    </html>
  );
}
